DefaultStorageEngine: SQLite
StorageEngine:
  SQLite:
    file: config/sqlite.sql
  JSON:
    file: config/users.json
files:
  - {sourceFile: /home/hpierce/code/cFun/, location: /cStuff/}
#  - {sourceFile: /home/hpierce/code/jse/, location: /angularTooling/}