Notifier:
  notificationLevel: 3 #0 - never, 1 - errors, 3 - always
  EmailNotifier:
    enabled: ~
    fromAddress:
    toAddresses: [  ]
    SMTPHost: smtp.gmail.com
    SMTPPort: 587
    SMTPEncryption: tls
    SMTPUserName:
    SMTPPassword:
DefaultStorageEngine: SQLite
StorageEngine:
  SQLite:
    file: config/sqlite.sql
  JSON:
    file: config/users.json
files:
  - {sourceFile: /home/hpierce/code, location: /code}
#  - {sourceFile: /home/hpierce/code/jse/, location: /angularTooling/}